### ISSUE TITLE
Use of "Similar Proprietary Products" field

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#100]
Feedback from email:

> The http://osgeo.getinteractive.nl/projects/qgis/ has a link to ESRI under "similar proprietary products". Is OSGeo advertising proprietary software? 

Content issue:

* [x] change the link to wikipedia entry, short-term "fix" (mailing list was still unhappy with this change)
* [x] leave it up to individual project teams if they wish to make use of the field

Action for getinteractive:

* [x] change "Similar Proprietary Products" to "Migrate From"
* [x] remove the ability to link
* [x] #108 provide a footer field to make a disclaimer about any registered trademarks (we need this anyway when refering to products for interoperability and file formats)

**Comment by jodygarnett** [comment]
The links, at least when I made them, point to the wikpedia entry on the product.

I am tempted to change this heading to say **Migrate from**.

**Comment by neteler** [comment]
@jodygarnett This was my private email, btw... I didn't intend to post it here.

**Comment by jodygarnett** [comment]
I see, I was sent the email and asked to report it as an issue. I have revised the description, hopefully capturing your original bug report.

Your feedback is totally on point, how can we better communicate what this is for? The original google form had a link to wikipedia as the example...

**Comment by venka-osgeo** [comment]
I think how our software compares with Proprietary Products is not an information to be provided on the OSGeo website. It can be shown on individual project pages as and where the PSC feels necessary. Our software is good because they are and not because they compare well with "Similar Proprietary Products", I think. I feel that the item "Similar Proprietary Products" could be removed.

**Comment by hellik** [comment]
I support and concur with Venka that the item "Similar Proprietary Products" should be removed. There isn't only one proprietary GIS software out there, there are several others. IMHO such comparisons may be part of e.g. a reviewed scientific paper/elaboration, where our OSGeo projects - if they want to - may link to. I see no added value for OSGeo to serve such links. As already elsewhere mentioned by me, reciprocity is the key if such items are listed, but I can't see this happen.

**Comment by jodygarnett** [comment]
I have done outreach at "normal" GIS conferences and this is the top question, how can I migrate from XXXX. Personally I answer that "I have not had the opportunity to use XXXX, what do you use it for? There are lots of open source options".

On a related note I need a hand writing the "what is open source" and "migrate to open source" pages.

Please keep in mind that this website is not for us who already know about open source, it is intended for visitors from the rest of the GIS industry, offering them a better way ...

**Comment by jodygarnett** [comment]
While I fixed the link, I am going to leave bug report open as the discussion is valuable. Marking this as *content* rather than a *bug* as we are using the ticket to discuss content provided by osgeo members rather than an issue with the website as implemented.

**Comment by strk** [comment]
I also think there should be no mention of proprietary software, not there.

While I understand the idea of "calling" people out of proprietary software I think doing so on the free software page is too late, because at that time they can already tell what the free software does.
It would work better something that only accepts proprietary software names as input from the user and only outputs free software alternatives. Can we provide that, based on input given by projects (maybe in a well-known yml file?)

Similar projects: http://www.makeuseof.com/tag/5-sites-to-find-free-alternatives-to-popular-software/

**Comment by kalxas** [comment]
I also agree that we should not mention proprietary software in our site.

**Comment by jodygarnett** [comment]
This is obviously a touchy subject for the OSGeo community; I am really not sure how to respond folks.

* I am concerned this response is based on the feeling we are somehow promoting proprietary software; instead of competing with it.

* If we do not provide a tool to help people migrate away from proprietary software we are not doing our job of promoting open source. This website, and these pages, are intended as that tool. 

@strk thanks for acknowledging the need, I think if we had the ability to filter projects by the "migrate from" field we could build your tool. But we do have to collect this information for the idea to work.

While providing a well-known yaml file is a good approach (rather than maintaining website pages) - but it will need to be a long term approach.

**Comment by cvvergara** [comment]
Suppose I have proprietary software, as such, I always pay for promoting my software.
I feel great when I get free promotion!!!

**Comment by jodygarnett** [comment]
I am not sure how to interpret your statement; I take it you view this as advertising and are critical. I would be critical if we were advertising; indeed this is why we revised our sponsors guidelines to prevent abuse earlier in the year.

@cvvergara our focus is on providing good service to visitors, helping them migrate to open source. In this case mentioning "Migrate From: ArcMap" does not mean we are promoting ArcMap.

**Comment by timlinux** [comment]
@jodygarnett Personally I agree with your thoughts that providing context for prospective users in the form of what similar software a given project compares to is a useful way for people to identify suitable packages. But given the lack of uniform opinion on this, I suggest just remove the field - not having it wont be a huge loss I guess.

**Comment by hellik** [comment]
@timlinux: citing my comment: "IMHO such comparisons may be part of e.g. a reviewed scientific paper/elaboration, where our OSGeo projects - if they want to - may link to."

In my experience, comparison of software/preparing context is more complex than on a first view it seems to be. Showing nice use case examples of raster-/vector-analysis and map production and example workflows are more helpful to new users than just simply serving a link to similar proprietary software (as this was the first concern in this discussion).

For example: sometimes the combination of open source software in your workflow are more powerful than some other monolithic software (e.g. preparing raster data by GDAL and then feed it e.g. to QGIS or GRASS GIS, etc).

What I've seen in GIS workshops, such fancy and nice use case examples and workflows lower the entry hurdle quite a lot for new users.

Putting this in a short blog or video, the outreach will increase.

**Comment by jodygarnett** [comment]
Thanks @timlinux and @hellik - given that we do not control this template (since the website is being produced under contract) how to you feel about:

* [ ] leave it up to individual project teams if they wish to make use of the field
* [ ] change the field to "Migrate From"
* [ ] remove the ability to link
* [ ] provide a footer field to make a disclaimer about any registered trademarks (we need this anyway when refering to products for interoperability and file formats)

I think that "migrate from" is suitably inclusive a phrase that this will work (and more importantly be helpful).

**Comment by jodygarnett** [comment]
@hellik providing comparisons is a great idea, to focus on the website these should be captured as "resources", and indeed these project pages may then link to them (either as resources or as part of the main description text).

**Comment by strk** [comment]
On Mon, Oct 02, 2017 at 01:12:48PM -0700, Jody Garnett wrote:
> Thanks @timlinux and @hellik - given that we do not control this template (since the website is being produced under contract) how to you feel about:

What do you mean we do not have control of the template ?
The website is completed, right ? Once we have the content
we can change everything, can't we ?

**Comment by jodygarnett** [comment]
@strk website is not complete, these issues are being reported against contract.

Things marked "enhancement" may be the subject of negotiation, things marked content we can edit (once SAC gets hosting sorted out).

You are correct that once the website is delivered we can make more detailed changes, but I would like to sort out what we can while we have get interactive available to do the work.

**Comment by strk** [comment]
I think keeping a "better replacement for proprietary product" is fine
to have in the form, as long as we don't advertise that product upon
display (using metadata keywords or link-less mentions...)

**Comment by jeffreylasut** [comment]
Issues in related bug #108 are squashed.
