### ISSUE TITLE
Footer field for references and registered trademark disclaimers

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#108]
The discussion around #100 has brought to our attention that use of product names ideally provide a disclaimer:

Non OSGeo product names are used:

- When describing compatibility and interoperability (for example support GDAL formats)
- Project descriptions "migrate from" field, if used
- Discussions of Interoperability, Hybrid Architectures and Migration

Action:

* [x] provide a footer field to make a disclaimer about any registered trademarks

Ideally this could be presented as a footer at the base of the page.

**Comment by jeffreylasut** [comment]
Disclaimer field added to projects, example:
http://osgeo.getinteractive.nl/projects/geonode/

**Comment by jodygarnett** [comment]
thanks, um could we make that much smaller - similar size to the website footer:

> © 2017 OSGeo - All rights reserved Legal information Colophon Design & Development by Get Interactive"

**Comment by jodygarnett** [comment]
I am reopening this issue after revising the http://osgeo.getinteractive.nl/projects/geonode/ page above to make the following requests:

* [ ] remove the heading disclaimer, not all uses of a footer will be a disclaimer, the area may also be used to cite references as noted in the issue title
* [ ] reduce the font size and visual appearance in keeping with the size of the website footer (this information supplementary and should not distract from the page content).

**Comment by jodygarnett** [comment]
Feedback from marketing email list:

> This is probably OK from a legal P.O.V, but now indeed ArcGIS feels a bit prominent in this page with the double mention. And as Windows and Mac are also mentionned, they should probably deserve their own (R). Ah nightmarish legal considerations...
>  
> Would that be possible to move the 'Disclaimer' (perhaps rename it to 'Legal mentions' at the bottom of the page (at least after the 'Service providers' section) ? or have just a 'Legal mentions' link that would go to a single page where we would put all that boring legal stuff and that would be common for all other project pages ?)
 
It is my hope that by reducing the size to that of a footer that we can avoid the need to reposition.

**Comment by jeffreylasut** [comment]
@svandenhaak Please configure the disclaimer field to be able to add links like the content field.
