### ISSUE TITLE
styleguide page 19 "png missing" for cartography example

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#109]
The [style guide](https://github.com/OSGeo/osgeo/blob/master/marketing/branding/styleguide-osgeo.pdf) Page 19 shows the following:

![png-missing](https://user-images.githubusercontent.com/629681/31141231-a56d1d4a-a82b-11e7-8f82-b8ec7eabf8d8.png)

**Comment by jodygarnett** [comment]
This is the only open issue against "Component 1 - Branding and Online Style Guide".

**Comment by jj0hns0n** [comment]
@petersongis can you help out?

**Comment by jj0hns0n** [comment]
![lowzoom2](https://user-images.githubusercontent.com/506078/31141869-73b0a93c-a82d-11e7-8904-f466e9c9e861.PNG)

**Comment by jodygarnett** [comment]
Thanks, I think Pim was asking for a stupidly hi-rez version (captured on an hidef display or something) so the result could be more print-ready.

**Comment by PetersonGIS** [comment]
I think this map is kind of ugly (full fault on me). I am working on a less ugly one and can submit as high-res.

**Comment by jodygarnett** [comment]
Understood @PetersonGIS, it is always nerve wracking providing an example to others. I hope we see the maps live on the site soon; and if we know where the styles are posted we can provide a link to "the latest" as part of this style guide (so you can relax a bit more).

While this PDF will be pretty the intention is to migrate to the website.

**Comment by PetersonGIS** [comment]
Ok. If you'd like, you can use this map instead (There's a 96 dpi and 300 dpi version). We will need to change the text that goes with the map.

![world_map_high_res](https://user-images.githubusercontent.com/5266205/31144537-514e81dc-a83e-11e7-96a4-db237ffd234e.png)
![world_map_low_res](https://user-images.githubusercontent.com/5266205/31144539-5155c276-a83e-11e7-9ad7-3d58878eb84b.png)

**Comment by bufferclip** [comment]
I like the design a lot :-)  Thanks for the map!!

Just some thoughts (**no** strong opinion at all)
* some countries are not labeled (labeling all countries is probably not possible due to the size of the map)
* we could remove the countries completely and label only the continents instead. This would make the map cleaner and would moreover show that we want to "overcome boundaries" ...

**Comment by PetersonGIS** [comment]
Fair points. How about these?
![world_map_high_res_alt1](https://user-images.githubusercontent.com/5266205/31149194-56e17c90-a84c-11e7-929d-997a5f101fbe.png)
![world_map_low_res_alt1](https://user-images.githubusercontent.com/5266205/31149195-56f086ea-a84c-11e7-91e5-1905cdc89b45.png)

**Comment by bufferclip** [comment]
Yes, I like it more. Thanks for changing it :-)

**Comment by Tintrin** [comment]
Thank you @PetersonGIS, I will add this to the syleguide.
