### ISSUE TITLE
StyleGuide lists incorrect light color, readme is correct

### ISSUE THREAD

**Issue by klassenjs** [OSGeo/osgeo#11]
The "For Web" hex and "Digital" decimal colors don't match for the Light color listed in the PDF.  The Readme appears correct.

https://github.com/OSGeo/osgeo/blob/master/marketing/branding/styleguide-osgeo.pdf
https://github.com/OSGeo/osgeo/blob/master/marketing/branding/README.md

PS: I'm looking at commit bb6dc57

**Comment by jodygarnett** [comment]
That is correct, it is a draft readme (from months ago) and I noted the problem for Pim.

If you spot anything else, or have any other feedback or requests for the style guide please speak up it is being worked on this week. 

So far feedback has focused on photos, cartography and examples for subbrands to consider when making their own logo.

**Comment by jodygarnett** [comment]
I have uploaded styleguide-osgeo-v4.pdf from pim correcting this issue.

There are still a number things to do, such as adding a cartography section.
