### ISSUE TITLE
news item share this icons missing on old news item in safari

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#117]
Checking:

- http://osgeo.getinteractive.nl/foundation-news/mapguide-open-source-1-1-0-released/

The share this icons are missing (using Safari 11.0 on macOS 10.13):

<img width="991" alt="share-this-missing" src="https://user-images.githubusercontent.com/629681/31182575-1aaa9aee-a8d9-11e7-9906-fa2cbb75b069.png">

**Comment by jeffreylasut** [comment]
It seems to be working on version 10.13.1.

![schermafbeelding 2017-11-01 om 15 06 45](https://user-images.githubusercontent.com/412658/32278918-7be28bce-bf17-11e7-9822-2fd425ec44d0.png)

**Comment by jodygarnett** [comment]
Oh darn - this bug report is totally my fault, I had Ghostery installed and it was blocking those widgets:

* AddThis: Widgets, Social
* Polyfill: Advertising
