### ISSUE TITLE
GeoForAll related news shows all news, should be restricted to the individual lab

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#122]
From discusion of #120:

> Yes, you are right: it is not clear enough. I also find confusing the "Related news" item as it is not "related" to the lab in particular but to OSGeo in general. But, again, despite this it's looking great!
> Thanks!
>
> Sergio Acosta y Lara

I think this we were just showing recent news to try out the layout, now that we are getting close to done can we restrict this to just news items related to the individual GeoForAll lab? (Same thing for open source projects, etc... )

**Comment by MarvinGI** [comment]
The Geo For All labs now only show related news. Relations for a news item can be managed in the Edit Foundation News screen.

**Comment by jodygarnett** [comment]
Thanks, we will have to hunt down examples.

Do you need similar reports for projects, partners and other places where 'related news' appears?

**Comment by jodygarnett** [comment]
I would like to verify, going to use the following as an example:
- http://osgeo.getinteractive.nl/geo-for-all-labs/university-colorado-denver/
- http://osgeo.getinteractive.nl/foundation-news/university-of-colorado-denvers-foss4g-lab/

So far I cannot get the related news section to change, it is still showing the generic news feed.

**Comment by jodygarnett** [comment]
Q: Do we expect the news item to have a link to the related 'university of colorado' page?

**Comment by MarvinGI** [comment]
My bad, I didn't pull the changes to the stage environment. Could you check again?

**Comment by jodygarnett** [comment]
Thanks Marvin, that looks great.

I note that the news item, where we fill in the association does not display the association, making a seperate enhancement for that.
