### ISSUE TITLE
When coordinates from Google Maps are converted to OpenLayers they are incorrect

### ISSUE THREAD

**Issue by MarvinGI** [OSGeo/osgeo#123]
We use this method to convert the coordinates we get from Google Maps to a format that is suitable for OpenLayers. But they seem to be incorrect.

```
function convertGoogleMapCordsToOpenLayerCords (lat, long) {
    return ol.proj.fromLonLat([long, lat]);
}
```
For example: http://osgeo.getinteractive.nl/local-chapters/

When you check the map you'll see the markers that are supposed to be on Brussels are located far more south.

**Comment by jodygarnett** [comment]
@MarvinGI I have asked for help on the marketing email list, and reached out to @ahocevar for help. I am leaving this issue unassigned until we can find a contributor to work on it.

**Comment by jodygarnett** [comment]
@ahocevar are you able to answer the specific question raised by this bug report, ie why coordinates, apparently obtained from google maps, appear too far south when displayed against an OSM basemap?

@MarvinGI when looking up locations I tend to use:

1. Look up the city on wikipedia, example https://en.wikipedia.org/wiki/Victoria,_British_Columbia

2. Look for the map on the right hand side, and click on the "coordinates": https://tools.wmflabs.org/geohack/geohack.php?pagename=Victoria,_British_Columbia&params=48_25_43_N_123_21_56_W_region:CA-BC_type:city

3. Read the "Decimal" representation: 48.428611, -123.365556 

Not saying this is a good way, just what I did when adding locations to the website.

Can you tell me how you obtained coordinates "from google earth" ?

**Comment by jodygarnett** [comment]
@MarvinGI can I confirm I am reading your code snippet correctly? The parameters say `(lat, long)` and the function call says `[long, lat]`?

Can you confirm you are swapping these around on purpose ... I know it sounds crazy but there can be reasons!

> Different "map projections" have the order of these two swapped around:
> 
> - science likes to have lat, long order - since latitude measured from the north start was easier to determine historically for ships at sea, and science like its measure with the most confience to come first. WMS 1.3.0 works this way.
> 
> - computer types like long, lat order - since we always think of the screen in terms of x / y positions.

**Comment by MarvinGI** [comment]
> @MarvinGI when looking up locations I tend to use:
>
> Look up the city on wikipedia, example https://en.wikipedia.org/wiki/Victoria,_British_Columbia
>
> Look for the map on the right hand side, and click on the "coordinates": https://tools.wmflabs.org/geohack/geohack.php?pagename=Victoria,_British_Columbia&params=48_25_43_N_123_21_56_W_region:CA-BC_type:city
> Read the "Decimal" representation: 48.428611, -123.365556
>
> Not saying this is a good way, just what I did when adding locations to the website.
>
> Can you tell me how you obtained coordinates "from google maps" ?

The decimal representation of the page you linked is the same type as on Google Maps. When you enter the coordinates on Google Maps you get the right location, when you enter the same coordinates in OpenLayers you get a location that is more south.

I obtained the coordinates from the google maps urls.  

> can I confirm I am reading your code snippet correctly? The parameters say (lat, long) and the function call says [long, lat]?
>
> Can you confirm you are swapping these around on purpose ... I know it sounds crazy but there can be reasons!

Yes, I'm swapping them on purpose because the OpenLayers functions require them in that order.

**Comment by ahocevar** [comment]
Where's the code for that map?

**Comment by MarvinGI** [comment]
This is the code for the map:

```
$(document).ready(function () {
        $.get(vars.adminUrl + '?action=getItems&postType=geo_for_all_lab&limit=-1&offset=0', function(response) {
            response = JSON.parse(response);

            updateMarkers(response.data);

        });

        var map = new ol.Map({
            view: new ol.View({
                center: [0, 0],
                zoom: 2
            }),
            layers: [
                new ol.layer.Tile({
                    source: new ol.source.OSM()
                })
            ],
            target: 'map'
        });

        map.once('postrender', function () {
            map.getView().setZoom(2);
        });

        function convertGoogleMapCordsToOpenLayerCords(lat, long) {
            return ol.proj.fromLonLat([long, lat]);
        }

        function updateMarkers(items) {
            var markers = [];

            for (var i = 0; i < items.length; i++) {
                var currentItem = items[i];

                if (currentItem.locations) {
                    for (var j = 0; j < currentItem.locations.length; j++) {
                        var lat = parseInt(currentItem.locations[j].lat);
                        var lng = parseInt(currentItem.locations[j].lng);

                        markers.push(new ol.Feature({
                            type: 'icon',
                            geometry: new ol.geom.Point(convertGoogleMapCordsToOpenLayerCords(lat, lng))
                        }));
                    }
                } else if (currentItem.location) {
                    var lat = parseInt(currentItem.location.lat);
                    var lng = parseInt(currentItem.location.lng);

                    markers.push(new ol.Feature({
                        type: 'icon',
                        geometry: new ol.geom.Point(convertGoogleMapCordsToOpenLayerCords(lat, lng))
                    }));
                }
            }

            var raster = new ol.layer.Tile({
                source: new ol.source.OSM()
            });

            var source = new ol.source.Vector({
                features: markers
            });

            var clusterSource = new ol.source.Cluster({
                source: source
            });

            var styleCache = {};
            var clusters = new ol.layer.Vector({
                source: clusterSource,
                style: function (feature) {
                    var size = feature.get('features').length;
                    var style = styleCache[size];

                    if (!style) {
                        style = new ol.style.Style({
                            image: new ol.style.Circle({
                                radius: 20,
                                fill: new ol.style.Fill({
                                    color: '#fff'
                                })
                            }),
                            text: new ol.style.Text({
                                font: 'bold 17px "Miriam Libre","Helvetica Neue",Helvetica,Arial,sans-serif',
                                text: size.toString(),
                                fill: new ol.style.Fill({
                                    color: '#003A40'
                                })
                            })
                        });

                        styleCache[size] = style;
                    }

                    return style;
                }
            });

            map.addLayer(clusters);
        };
    });
```

**Comment by ahocevar** [comment]
And where is the result? I don't find a map on http://osgeo.getinteractive.nl/local-chapters/.

**Comment by ahocevar** [comment]
I found your issue @MarvinGI. You're doing `parseInt` for geographic coordinates, so you're stripping down precision to degrees. Change that to `parseFloat`.

**Comment by jodygarnett** [comment]
See https://github.com/OSGeo/osgeo/issues/128 for list of webmaps on the site and how to use.

**Comment by MarvinGI** [comment]
> I found your issue @MarvinGI. You're doing parseInt for geographic coordinates, so you're stripping down precision to degrees. Change that to parseFloat.

Totally missed that. The markers look right after changing the parse. Thank you.
