### ISSUE TITLE
Colors in Branding Style Guide are not consistent

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/osgeo#13]
The page 9 of the Branding Style Guide shows the two main colors in the logo and as squares, but these don't fit with "for digital" and "for web" definitions.

Text says: `#4cb05b #00393F`
Colors are: `#4dbf5e #12343A`

Image shows the difference (part of page 9 modified in Inkscape):

![styleguide_colors](https://user-images.githubusercontent.com/5449060/29140192-a2820da0-7d17-11e7-9217-76ae54417233.png)

I don't have a good way to check the "for print/press" and "for printingpress" right now.

The rest of the guide seems to use the values I acquired from the boxes (or logo), not the one from the text.

**Comment by jodygarnett** [comment]
The style guide was updated at about the same time as you reported this issue, can you confirm you are still seeing this inconsistency?

https://github.com/OSGeo/osgeo/blob/master/marketing/branding/styleguide-osgeo.pdf

**Comment by wenzeslaus** [comment]
Yes. The same inconsistency as before. Slightly different actually (`#4CBF5D #12343A`). When viewing the PDF directly on GitHub, I get different colors (`#4CBE6B #0B373D`) in Firefox and Chromium, I don't know why is that, but regardless I would trust more the desktop view than the GitHub view.

**Comment by Tintrin** [comment]
You get inconsistency with different browsers. Not really a way to avoid that. But the main difference within the pages are the arrows (branding elements - footer and hero image) now. This occurs with compressing to .jpg or .png. We will change this to .svg where we can adjust the colours with code.

**Comment by Tintrin** [comment]
You get inconsistency with different browsers. Not really a way to avoid that. But the main difference within the pages are the arrows (branding elements - footer and hero image) now. This occurs with compressing to .jpg or .png. We will change this to .svg where we can adjust the colours with code.

**Comment by Tintrin** [comment]
You get inconsistency with different browsers. Not really a way to avoid that. But the main difference within the pages are the arrows (branding elements - footer and hero image) now. This occurs with compressing to .jpg or .png. We will change this to .svg where we can adjust the colours with code.
