### ISSUE TITLE
No maps shown on iPhone 6 Plus

### ISSUE THREAD

**Issue by vloemans-marc** [OSGeo/osgeo#136]

**Comment by jeffreylasut** [comment]
@vloemans-marc Could you provide which iOS version you are using?
You can find it at Settings->General->About.

**Comment by jeffreylasut** [comment]
Version IOS 11.1 is used by Marc

**Comment by jeffreylasut** [comment]
Tested on IOS 11.03, it seems to be working fine.
@vloemans-marc Coulf you please check again if the map on http://osgeo.getinteractive.nl/initiatives/geo-for-all/.
Please try to clear your browser cache if the problem persists.

**Comment by vloemans-marc** [comment]
It works ! Thx. 

Kind regards,
Marc Vloemans
