### ISSUE TITLE
Who's involved view all link

### ISSUE THREAD

**Issue by jeffreylasut** [OSGeo/osgeo#138]
The "View all" link goes to the members page but doesn't filter by project or lab.

http://osgeo.getinteractive.nl/projects/geonode/

**Comment by jodygarnett** [comment]
Similar issue with local chapters.

Similar to #149 filter settings are not captured as part of URL.

**Comment by jodygarnett** [comment]
I see a similar fox has been provided for service providers:

http://osgeo.getinteractive.nl/service-providers/?p=geonode

Notes:
- filter geonode cannot be set with dropdown 
- not sorted according to core > contributor > other 

I will make a new ticket I guess.
