### ISSUE TITLE
partners list shows website links, but individual pages do not!

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#139]
Related pages: 

* http://osgeo.getinteractive.nl/partners
* http://osgeo.getinteractive.nl/partners/igu/
* etc...

Partner card showing website URL:

![igu-card](https://user-images.githubusercontent.com/629681/31722886-23798a5a-b3d2-11e7-833f-e7292a6c08e3.png)

**Comment by jodygarnett** [comment]
This is probably a duplicate of #94

**Comment by svandenhaak** [comment]
Partners which make use of the website input field, now automatically have a call-2-action button on the individual page.
