### ISSUE TITLE
Use of "OSGeo" in menus and actions (rather than "OSGEO")

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#146]
As reported by our president:

> "OSGEO" needs to be changed to "OSGeo" at several places in
> 
> http://osgeo.getinteractive.nl/
> 
> I think, I had mentioned this before. If all-caps is because of the font-face being used, changing the font could kindly be considered.
> 
> Best
> 
> Venka

**Comment by jodygarnett** [comment]
I wonder if "small caps" could be used as a compromise (but perhaps that is just silly).

**Comment by jodygarnett** [comment]
@jeffreylasut marking this as a bug to remind us to discuss as next meeting, if we can handle it via the issue tracker that is okay too.

I looked in our meeting notes, since I remember discussing this when venka origionaly reported it. In this case we have a conflict between visual consistency (capital presentation for actions and menus) and corporate identity "OSGeo".  Do you think Pim would go for small caps as a compromise?

**Comment by jeffreylasut** [comment]
@jodygarnett Discussed it with Pim and we go for "not forcing capitals" on the menu's and call-2-action buttons.
Made a little example how it will look:
![lowercase-example](https://user-images.githubusercontent.com/412658/31878815-962e7332-b7db-11e7-9e83-6a1a8b708066.png)

**Comment by jodygarnett** [comment]
I have asked Venka to review the above image, hopefully in time for tomorrows meeting.

**Comment by jodygarnett** [comment]
I did not even notice this fix until hitting refresh
