### ISSUE TITLE
Make Initiative for OSGeo participation in Google Summer of Code

### ISSUE THREAD

**Issue by cvvergara** [OSGeo/osgeo#15]
Can this repository be used also to store a promotional poster of the: OSGeo-GSoC program?

**Comment by jodygarnett** [comment]
Of course, I think that would be good to mark down as an initiative (similar to GeoForAll and OSGeo Live). Do you want to make a page for Google Summer of Code?

It is up to you if you want to do an initiative or have an osgeo committee, both work okay, committees are a bit more internal, initiatives should have an outreach focus.

**Comment by jodygarnett** [comment]
Can you see clarification @cvvergara and then make the appropriate page :)

**Comment by jodygarnett** [comment]
This is a content reqest, marking as "help wanted" since I cannot manage to make custom labels.

**Comment by cvvergara** [comment]
@jodygarnett 
We, the current mentors & GSoC admins, are working on the poster

**Comment by jodygarnett** [comment]
Changed to content (thanks @jeffreylasut for figuring out labels).

@cvvergara you should be able to make a GSOC initiative page when the website goes live.

**Comment by jodygarnett** [comment]
@cvvergara it looks like I can now make menus, is there a wiki page or something I could use to have some text for a placeholder page?

**Comment by jodygarnett** [comment]
I think this can be closed: http://www.osgeo.org/initiatives/gsoc/
