### ISSUE TITLE
geoforall map interrupts page scroll 

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#150]
When scrolling down the following page using the mouse scroll wheel:

* http://osgeo.getinteractive.nl/initiatives/geo-for-all/

The scroll action is captured by the map and used to zoom; making it hard to reach the end of the page!

This is more a challenge on mobile, once your screen enters the map ... you can never leave!

Options:

- Double click action can also be used to zoom the map
- On mobile map should be using pinch to zoom and not be affected

**Comment by jeffreylasut** [comment]
@MarvinGI please setup a meeting with @ahocevar to fix this problem.

**Comment by jodygarnett** [comment]
Looks like this is a one liner: https://gis.stackexchange.com/questions/136782/how-do-i-disable-mouse-scroll-zoom-in-openlayers-3

```
var map = new ol.Map({
  interactions: ol.interaction.defaults({mouseWheelZoom:false}),
  ...
});
```

**Comment by jeffreylasut** [comment]
@jodygarnett This is added to the website http://osgeo.getinteractive.nl/initiatives/geo-for-all/
On desktop this solves the scrolling issues, but not for mobile/tablet.

**Comment by jodygarnett** [comment]
Okay we need to ask @ahocevar for help

**Comment by ahocevar** [comment]
Here's a solution that works for both desktop and mobile:
```js

var map = new ol.Map({
  interactions: ol.interaction.defaults({
    mouseWheelZoom:false,
    dragPan: false
  }),
  ...
});

function onMouseMove(e) {
  documnent.removeEventListener('mousemove', onMouseMove, false);
  map.addInteraction(new ol.interaction.DragPan());
}
document.addEventListener('mousemove', onMouseMove, false);
```
Mobile users will then need two fingers to pan the map, which has become default behaviour in similar apps that use Google Maps as well.

**Comment by jeffreylasut** [comment]
issue is solved.
