### ISSUE TITLE
Project page sevice providers link, list not sorted core > contributor > other

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#159]
Follow on to #138 - I see a similar fix has been provided for service providers:

http://osgeo.getinteractive.nl/service-providers/?p=geonode

Notes:
page
- [x] bug: doesn't seem to filter by project (View all service providers in project detail)
- [x] bug: not sorted according to core > contributor > other 

The following things were missed from wireframe review and have been taken to #161:
- [ ] functionality: filter geonode cannot be set with dropdown, but works when linked from project 
- [ ] enhancement: we do not have any kind of badging for core contributor other

**Comment by MarvinGI** [comment]
We fixed the bugs.

**Comment by jodygarnett** [comment]
Checking wireframes, we only have an early wireframe listing service providers, it has a drop down listing project expertise.
