### ISSUE TITLE
Support for non osgeo projects

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#16]
The project marker is limited to "OSGeo Project" and "OSGeo community" markers. Not all open source spatial projects are from our organization, please expand this list to include:

![project-options](https://user-images.githubusercontent.com/629681/29179495-75266d78-7da9-11e7-8571-e3a1f7c4d335.png)

Here is the affected page - http://osgeo.getinteractive.nl/projects/jts/

**Comment by jodygarnett** [comment]
http://osgeo.getinteractive.nl/projects/osgeo-live/ <-- no project affiliation
http://osgeo.getinteractive.nl/projects/jts/ <-- locationtech

**Comment by jeffreylasut** [comment]
added the option Other...

**Comment by jodygarnett** [comment]
Thanks, would also like to have LocationTech and KDE (so those projects can be branded with the appropriate logo).

**Comment by jodygarnett** [comment]
This is now resolved, the default radio button is still "OSGeo project" leading many projects to miss list themselves.
