### ISSUE TITLE
OSGeo wiki page Logo - add information about the new logo

### ISSUE THREAD

**Issue by astroidex** [OSGeo/osgeo#163]
* add information to the OSGeo Logo Wiki page https://wiki.osgeo.org/wiki/Logo
* the page logo contains information about the branding (till 2017)
* I added short information about the new logo and referenced to github. 
* please check whether it is enough information

**Comment by jodygarnett** [comment]
I think we can remove the information on the old logo. What I tried to do for the GetHub readme files is quote the style guide (and provide a link to the style guide).

I had a question @astroidex - we have two things to communicate: a) the use of the logo (to represent OSGeo) and b) the use of a sub-brand (to represent an OSGeo activity). Is it worth covering these on the same page, or will it only confuse?

**Comment by jodygarnett** [comment]
I think we can also remove the contents of https://wiki.osgeo.org/wiki/TrademarkGuidelines linking to the (which link to the appropriate website trademark guidelines page).

Duplicating information, or providing historical information, does not help (most times a community member searches they are seeking quick clarification).

**Comment by astroidex** [comment]
* +1 to remove content of TrademarkGuideline and link to style guide. historical information will still be in the wiki-history

**Comment by jodygarnett** [comment]
Revised both pages, please close if you are content with the change

**Comment by astroidex** [comment]
great. less is sometimes more ;)
