### ISSUE TITLE
Topic organization randomized after editing

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#166]
The topic choose for this page:

- http://osgeo.getinteractive.nl/projects/deegree/

Is hard to sort out after editing, since the items in the list seem to be reordered - irregardless of topic nesting.

![topic-order](https://user-images.githubusercontent.com/629681/32827703-ee4f41fe-c9a1-11e7-9756-87327265c3fe.PNG)

In the picture above "raster processing" should be nested under Analysis and Processing.

**Comment by jodygarnett** [comment]
Can sorting of these labels be turned off?

**Comment by jodygarnett** [comment]
okay solution is to select the parent

**Comment by jodygarnett** [comment]
Going to guess this is not fixable, just part of how word press operates, selecting the "parent" tag makes this slightly easier to follow for subsequent edit.

Action suggestion - check for a wordpress bug report and cross link, or make a wordpress bug report.

**Comment by MarvinGI** [comment]
I've added code to custom which prevents that checked taxonomies are moved to the top of the list. They now stay in the same position checked or not checked.

**Comment by jodygarnett** [comment]
That is great @marvinGI I was not sure this one would be fixable; I cannot login to check but I will mark this one as closed.
