### ISSUE TITLE
update new version of OTB in OSGEO4W

### ISSUE THREAD

**Issue by siglagglo** [OSGeo/osgeo#167]
Hi,
I would like to install the last version of otb 6.2 (or at least 6.0) with OsGeo4W but i notice that the last version available is 5.0 and is not up to date. So several algorithms are missing in qgis geoprocessings interface.
Thanks for soleving this issue.

**Comment by jodygarnett** [comment]
This issue tracker if for the osgeo.org website, the issue tracker for OsGeo4W is here - https://trac.osgeo.org/osgeo4w/
