### ISSUE TITLE
Component 2: Local Chapter Page Event listing and event calendar integration

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#168]
Reviewing component 2 deliverables, seeking to verify the following:

3.3.2.4 Local Organizations

* [x] Local Chapters index using a map based interface;
* [x] Local detail page with events, news and social media feeds related to local chapter
* [x] Local organizations are able to add events to the events calendar

Example pages for reference:

* http://osgeo.getinteractive.nl/local-chapters/gfoss-it/
* http://osgeo.getinteractive.nl/local-chapters/cugos/
* http://osgeo.getinteractive.nl/local-chapters/foss4g-philippines/
* http://osgeo.getinteractive.nl/local-chapters/geo-spatial-org/

**Comment by jodygarnett** [comment]
Functionality for "index using a map based interface" is done

The map is hidden behind the drop down filter and not easily discoverable (the filter drop down has a toggle map button). Marking this as done, although we should consider placing a "toggle map" button right next to filter to make the discovery of the functionality easier.

<img width="1232" alt="togglemap" src="https://user-images.githubusercontent.com/629681/33053352-2eba7900-cec7-11e7-918a-c7167e19fdb8.png">

**Comment by MarvinGI** [comment]
When editing a event relations to local chapters can now be added under de relations tab.

For testing purposes I added an event to:
http://osgeo.getinteractive.nl/local-chapters/gfoss-it/

The event can be edited here:
http://osgeo.getinteractive.nl/wp-admin/post.php?post=4113&action=edit

**Comment by jodygarnett** [comment]
Thanks that looks perfect.

One note before I close this: related news has "view all press releases" as a link for more, would be more correct to say "view all news".

**Comment by cvvergara** [comment]
@jodygarnett 
shouldnt we be using:
https://staging.www.osgeo.org/

**Comment by MarvinGI** [comment]
> One note before I close this: related news has "view all press releases" as a link for more, would be more correct to say "view all news".

I have changed the text.
