### ISSUE TITLE
Component 2: Initiative Page showing resources and news

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#169]
Reviewing component 2 deliverables, seeking to verify the following:

3.3.2.5 Initiatives

* [x] Initiatives index (highlight OSGeo foundation key initiatives high level way)
* [x] Initiative detail page with resources and news.

Example pages for reference:

* http://osgeo.getinteractive.nl/initiatives/ - lists initiatives, although dropdown menu used more often
* http://osgeo.getinteractive.nl/initiatives/foss4g/ - this is normal page resources and news added by hand

**Comment by jodygarnett** [comment]
The initiatives page is a simple page with links (rather than a card page), initiatives have their own navigational menu so discoverability will be high.

**Comment by MarvinGI** [comment]
Related and resources can now be added with a relationship field in edit screen of the initiative page.

For example:
http://osgeo.getinteractive.nl/initiatives/foss4g/

**Comment by jodygarnett** [comment]
Thanks, that looks fine.
