### ISSUE TITLE
Component 2: Downloads

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#170]
Reviewing component 2 deliverables, seeking to verify the following:

3.3.2.8 Downloads (moved to resources)

* [ ] Downloads index;
* [ ] Download detail with links to project detail page

Example pages for reference:

* http://osgeo.getinteractive.nl/resources/ - lack ability to provide URL restricting resource type to download
* (We lack an example of a "download" resource item)

**Comment by jodygarnett** [comment]
I am pretty sure if I had edit access I could make a "download" resource type and close this issue out.

**Comment by jeffreylasut** [comment]
Example resource with a download:
http://osgeo.getinteractive.nl/resources/ogc-memorandum-understanding/

**Comment by jodygarnett** [comment]
I see, that is when the issue is "attached" to the website.

@jeffreylasut I think we are better served by the [geoserver project page](http://osgeo.getinteractive.nl/projects/geoserver/) where there is a download software link meeting this requirement.

@jj0hns0n can you comment or clarify on this requirement please?

**Comment by jodygarnett** [comment]
Going to mark this as won't fix, the "solution" would be to make a resource type "download", and then allow the resource page to have a stable link for downloads, listing the latest download page for each project only.

Think we prefer to have the "Download software" link above, making this managed by each project team.
