### ISSUE TITLE
Component 2: Events index with list and calendar view

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#171]
Seeing to verify the following component 2 deliverable:

3.3.2.10 Events

* [ ] Event index with a list and calendar view;
* [ ] Event detail page with social media feeds, hashtags and photo streams;

Links:

* http://osgeo.getinteractive.nl/events/ - event list, no calendar view
* http://osgeo.getinteractive.nl/events/foss4g-sotm-argentina-2017-buenos-aires-argentina/ - prior event still listed
* http://osgeo.getinteractive.nl/events/osgeo-code-sprint-2018/ - upcoming event

**Comment by jodygarnett** [comment]
The event index is listing prior events, while it does not have a calendar view it *is* sorted by date easier to find what is going on when. Is sorting by date enough to cover the "calendar view" functionality.

**Comment by jodygarnett** [comment]
The event detail page does not provide social media feed, hashtags, photo streams (ie all the kind of things that would be filled in by our community when an event is running).

**Comment by MarvinGI** [comment]
> The event index is listing prior events

This is fixed now. The list only contains events that are in the present or future.

**Comment by jodygarnett** [comment]
Thanks going to mark this as resolved.

**Comment by jodygarnett** [comment]
Marked the social media feed integration as https://github.com/OSGeo/osgeo/issues/173
