### ISSUE TITLE
Unable to crop sponsor logo on staging

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#174]
Attempting to set up safe software as a new sponsor with the following logo:

![safe_rgb](https://user-images.githubusercontent.com/629681/34219784-29341b1a-e567-11e7-9d1a-5c1a1b1232c9.png)

As usual this requires cropping, however when selecting a valid area and pressing crop Wordpress remains stuck on the form and I am unable to proceed as shown below.

![sponsor-crop-stuck](https://user-images.githubusercontent.com/629681/34219830-5b19deee-e567-11e7-8153-aab9b1e8201d.png)

**Comment by jodygarnett** [comment]
This issue occurs in Safari and Firefox.

**Comment by jodygarnett** [comment]
By making the image smaller than the requested 740x412 images I got a warning, and avoided the crop screen. The resulting image is stretched but visible here: https://staging.www.osgeo.org/sponsors/

**Comment by jodygarnett** [comment]
This same issue with the crop button is preventing members from setting an avatar image.

**Comment by MarvinGI** [comment]
@jodygarnett I fixed the issue locally by installing the PHP GD Library. For php 7.0 the command to install this library is `sudo apt-get install php7.0-gd`.

**Comment by jodygarnett** [comment]
Related to https://trac.osgeo.org/osgeo/ticket/2057 crop not working for sponsors page

**Comment by jodygarnett** [comment]
Thanks @MarvinGI installing that (for php5) helped and we can now crop the safe software logo.

However the sponsors page (https://staging.www.osgeo.org/sponsors/) no longer shows *any* sponsor logos so we may have an incompatibility?

**Comment by jodygarnett** [comment]
Answer was easier the 2017 sponsors no longer are shown as intended. We are looking at add a month field ...
