### ISSUE TITLE
staging.www.osgeo.org fails to show fonts on Firefox Quantum

### ISSUE THREAD

**Issue by neteler** [OSGeo/osgeo#175]
![fonts_missing_staging_site](https://user-images.githubusercontent.com/1295172/34297651-affc267a-e719-11e7-803f-1042a0ff5919.png)

... this happens due to the external embedding of Google fonts.

Please change to self-hosting of the Google fonts, also to avoid external tracking of our users (may also collide with the upcoming EU General Data Protection Regulation).

To test: install for example the "uBlock origin" plugin. All other web sites I visit do not have such an lack-of-fonts issue, never seen before except for the new staging site.

**Comment by jodygarnett** [comment]
Checking on stack exchange their are several solutions for self hosting google fonts.

* https://google-webfonts-helper.herokuapp.com/
* https://stackoverflow.com/questions/8966740/how-to-host-google-web-fonts-on-my-own-server/31801634#31801634

**Comment by neteler** [comment]
Update: I used the Firefox (Quantum) Inspector and checked the font.

When I change "Miriam Libre" to "Miriam", then all written text shows up!

Just saw https://github.com/google/fonts/issues/1300 (I am on Linux, though).

**Comment by neteler** [comment]
See also https://github.com/OSGeo/osgeo/issues/154

**Comment by neteler** [comment]
Found it: a local glitch due to local font installation needed for the OSGeo branding stuff...

Hence: invalid.

**Comment by jodygarnett** [comment]
@neteler can you clarify? In case the next person runs into trouble ...

**Comment by neteler** [comment]
Sure: the local copy of Miriam fonts was broken after laptop update :( Their installation was needed some weeks ago to get the marketing material done. Later I forgot about the local copy in $HOME/.local/fonts/ which caused the problem. Just today I remembered about them and checked - voilà, broken. After broken font files removal the new site is shiny as expected.

**Comment by jodygarnett** [comment]
Wonder if that would help #154 ?
