### ISSUE TITLE
staging.osgeo.org getting started page links need to be fixed

### ISSUE THREAD

**Issue by robe2** [OSGeo/osgeo#177]
In going thru this page and fixing the ldap links I noticed a lot of hard-coded www.osgeo.org links which will no longer work when this site goes live.

These need to be changed to relative links

https://staging.www.osgeo.org/community/getting-started-osgeo/

**Comment by cvvergara** [comment]
I modified the page, I think the links are ok now.
@jodygarnett can you verify please?

**Comment by jodygarnett** [comment]
That is great, I cannot think of a good way to verify (been clicking on random things). How did you fix?

(Going to mark as closed and we can reopen if we find a broken link)

**Comment by cvvergara** [comment]
I clicked on all links, had to create a new page that will not exist when the site is moved to the final location.

**Comment by jodygarnett** [comment]
So chances are we will find some more when we move. @robe2 indicated she may be able to bulk fix links after the move, perhaps she has some ideas to help...
