### ISSUE TITLE
Add image button not working when setting member avatar

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#178]
As per #174 members are reporting being unable to set an avatar image when logging in with their "osgeo id" LDAP credentials for the first time:

Examples:

- https://staging.www.osgeo.org/member/davis/
- https://staging.www.osgeo.org/member/aime/

Report:

> The "add image" button does nothing, when clicking it I get the following in the javascript console:
>
> > TypeError: wp.media is undefined
>
> So it seems to be a setup error in the website

We may be able to configure https://en.gravatar.com to work?

**Comment by jodygarnett** [comment]
Related to https://trac.osgeo.org/osgeo/ticket/2057 crop not working for sponsors page

**Comment by jodygarnett** [comment]
Crop issue is fixed, marking these as closed.

**Comment by astroidex** [comment]
maybe we should reopen this ticket
* looks like normal Subscribers can't upload an image. My collegues tried it but nothing happens, no error message
