### ISSUE TITLE
Combine Project and Topics and Technologies

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#19]
I am finding projects like QGIS and OSGeo-Live incorrectly listing themselves as it is not obvious that Level 1 Topics and Level 2 Technologies are related.

I noticed when editing Technologies "Integrated" --> "Portal" that individuals items can form a tree. Can we change to the following tree structure to prevent confusion?

Topics
```
Publish
- Content Management
- Catalog
- Data
Mapping and Cartogrpahy
- Desktop Mapping
- Mapping Services
- Mobile Mapping
Analysis and Processing
- Desktop Anaysis
- Web Processing
- Data Query
- Raster Processing
Information Technology
- Data
- Web Services
- Client
- Cloud
- Portal
Development
- Web Development
- Tools
- Libraries
- Mobile Development
```  

Technologies can then be removed, since it is causing confusion for projects trying to list themselves
```

```

**Comment by jodygarnett** [comment]
Okay I am excited about this change, it will make the choose a project classification much easier to manage

**Comment by jeffreylasut** [comment]
All topic titles are changed as suggested.

**Comment by jodygarnett** [comment]
Not sure we communicated well, I am talking about"

a) Removing "Technologies"
b) Using the "Parent Category" field to produce the tree structure using child topics

![sub-topic](https://user-images.githubusercontent.com/629681/29214422-2048b708-7e5c-11e7-8cca-570bcbacb8cd.png)

**Comment by jodygarnett** [comment]
A good idea, but breaks the filter sytem.

The existing approach is better as "cartography + mobile" and "development + mobile" can both be accomplished in the filter without duplication.

**Comment by jodygarnett** [comment]
Going to reopen as the choose-a-project cannot work as written; it combines all the tags rather than use them to fitter as planned. The approach mentioned on this ticket is one way to fix this.

<img width="400" alt="project-tags" src="https://user-images.githubusercontent.com/629681/29334958-2470cdf6-81d7-11e7-8033-a056b4a6dc70.png">

The above settings should show only PostGIS

**Comment by jodygarnett** [comment]
See also https://github.com/OSGeo/osgeo/issues/88

**Comment by jodygarnett** [comment]
Reopened based on meeting review of initial projects from sprint.

The Level 1 > Level 2 is not being consistently applied leaving some page.

**Comment by jodygarnett** [comment]
Note it would be fine to *remove* Topics from the Filter menu, a similar role is already played by Category, Technology and Development.
