### ISSUE TITLE
There is no Platinum type of sponsor

### ISSUE THREAD

**Issue by Delawen** [OSGeo/osgeo#198]
Hi,

I tried to add GeoCat as Platinum sponsor, but there is no such type, although it is defined here: https://www.osgeo.org/about/how-to-become-a-sponsor/

I couldn't find any place on the source code where this list is, I guess it should be on the database. But I couldn't find a way to add it from the dashboard, maybe I don't have privileges to see the type definition?

In any case: Platinum type of sponsorship has to be added.

// @cvvergara

**Comment by cvvergara** [comment]
Added Platinum in the sponsor category
https://trac.osgeo.org/osgeo/ticket/2190

Just made GeoCat Platinum

**Comment by Delawen** [comment]
Thanks!
