### ISSUE TITLE
How can I connect events to local chapters?

### ISSUE THREAD

**Issue by astroidex** [OSGeo/osgeo#20]
On the local chapters page it says Events

* http://osgeo.getinteractive.nl/local-chapters/fossgis-e-v/

How can I connect an event to a local chapter so that it shows up at the local chapters page?

**Comment by jeffreylasut** [comment]
@astroidex You can do this by adding a event (http://osgeo.getinteractive.nl/wp-admin/edit.php?post_type=event) and in the tab initiative you select the local chapter.

**Comment by astroidex** [comment]
Hi @jeffreylasut - thanks for the info.
