### ISSUE TITLE
OSGeo LinkedIn URL invalid on osgeo.org 

### ISSUE THREAD

**Issue by SunveerSingh** [OSGeo/osgeo#231]
On https://www.osgeo.org/ at the bottom of the page under the Find Us On section, LinkedIn takes us to this link: https://www.linkedin.com/company-beta/3338753/ while our LinkedIn is: https://www.linkedin.com/company/osgeo/

I will be happy to fix this and make a pull request, where can I find appropriate files?

**Comment by astroidex** [comment]
Hello @SunveerSingh Thanks for the info. We will fix this. It has to be done in wordpress so no PR possible.

**Comment by cvvergara** [comment]
@SunveerSingh 
Can you check it is fixed please (I dont have linkedin account, and do not have plans to open one)

**Comment by SunveerSingh** [comment]
@cvvergara Yes, it is totally fine now.
