### ISSUE TITLE
Can't edit the wiki

### ISSUE THREAD

**Issue by jidanni** [OSGeo/osgeo#235]
https://wiki.osgeo.org/w/index.php?title=Taiwan_datums&action=edit says

> You do not have permission to edit this page, for the following reason:
> 
> The action you have requested is limited to users in one of the groups: Users, emailconfirmed.

https://wiki.osgeo.org/wiki/Special:Preferences says

> Member of groups:Accounts in progress of converting, Accounts that have been merged, Old wiki accounts, Autoconfirmed users, Users

https://wiki.osgeo.org/w/index.php?title=Special%3AUserRights&user=Jidanni says

> Member of: Accounts in progress of converting, Accounts that have been merged, Old wiki accounts
> 
> Implicit member of: Autoconfirmed users

**Comment by jidanni** [comment]
https://wiki.osgeo.org/wiki/OSGeo:Users doesn't list me. Nor can I figure out how to confirm my email again.

**Comment by pesekon2** [comment]
@jidanni I am facing the same issue. Have logged in after a year or so, followed the LDAP migration steps, and now I'm unable to edit any page - ironically, I cannot edit even my own profile now.

**Comment by neteler** [comment]
The issue is handled in https://trac.osgeo.org/osgeo/ticket/2599 . Pls comment there.

**Comment by pesekon2** [comment]
@neteler Great, my issue solved individually in the ticket. Thanks.
