### ISSUE TITLE
Broken Contributors Link on the QGIS Project Page

### ISSUE THREAD

**Issue by lujoh** [OSGeo/osgeo#236]
The Contributors link on the page [https://www.osgeo.org/projects/qgis/](https://www.osgeo.org/projects/qgis/) is leading me to a 404 not found error. The link in question is in the End User Resources Section and the broken URL is [https://github.com/qgis/QGIS/blob/master/doc/contributors.json](https://github.com/qgis/QGIS/blob/master/doc/contributors.json)

Please let me know if I'm posting this in the wrong place.

**Comment by astroidex** [comment]
Fixed
Link goes to https://github.com/qgis/QGIS/blob/master/doc/CONTRIBUTORS

**Comment by astroidex** [comment]
Done
