### ISSUE TITLE
Member Profile - Select Member Type and recognition of member participation

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#25]
This is single selection which does not reflect our needs (personally I am a charter member, committee member and project steering committee member).

Options to resolve:

* [x] Use checkboxes, see #42
* [ ] Use a single **charter member**  checkbox - relying on cross link to project pages, and committee pages and geoforall labs to capture member participation.

Examples:
- http://osgeo.getinteractive.nl/member/jody-garnett/

Related issues:

* Duplicate: #42
* Enhancement: #14 Request for more participation icons on member page

**Comment by svandenhaak** [comment]
The first issue has been solved, member type now uses checkboxes instead of radio buttons. 
I'm not sure I understand what you mean with the second issue, could you please elaborate?

**Comment by jodygarnett** [comment]
The second checkbox was an idea on how we could make this easier; the **member type** tried to list what activities a person was involved in. The other way to do so is with cross links, so if they are on a committee they are cross linked to the committee page.

Actually we can see how this works - it is how projects are handled now.

In the following screen snap:

* Member Type and Select Member Type are duplicate
* Member Type *project* and selecting from the *Projects* list are duplicate
* Member type *committee* could be replaced by allowing the member to select from a list of committee pages (they may belong to more that one committee).

<img width="992" alt="member" src="https://user-images.githubusercontent.com/629681/30749711-13533fa4-9f69-11e7-84a0-9171eb8599b1.png">




Examples:
- http://osgeo.getinteractive.nl/member/jody-garnett/
- http://osgeo.getinteractive.nl/projects/geoserver/
-

**Comment by svandenhaak** [comment]
Thank you for your explanation.

- Select member type has been removed (the reason it was still visible (and thus duplicate), was because it's still used in the backend).
- The project checkbox has been removed. Members can now be filtered by the projects they are associated with.
- The committee checkbox has been replaced with a list of committees. Members can now be filtered by the committees they are associated with.
