### ISSUE TITLE
Proj.db version mismatch

### ISSUE THREAD

**Issue by gpsaliola** [OSGeo/osgeo#254]
Hello,
I've a problem with osgeo4w-setup.exe evergreen installation since few days ago.
I've installed with this command:
osgeo4w-setup.exe -q -A -a x86_64 -k -L -d -n -N -D -s https://download.osgeo.org/osgeo4w/v2 -C Commandline_Utilities -x shell -P gpsbabel-gui -P gdal -P proj
I obtain this when I use gdal_translate.exe utility.
"missing l4z.dll".

If I install with this command:
osgeo4w-setup.exe -q -A -a x86_64 -k -L -d -n -N -D -s https://download.osgeo.org/osgeo4w/v2 -C Commandline_Utilities -x shell -P gpsbabel-gui -P gdal -P lz4 -P proj
I obtains this error:
Warning 1: PROJ: proj_create_from_database: C:\OSGeo4W\share\proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 1 whereas a number >= 3 is expected. It comes from another PROJ installation.
Warning 1: The definition of projected CRS EPSG:3857 got from GeoTIFF keys is not the same as the one from the EPSG registry, which may cause issues during reprojection operations. Set GTIFF_SRS_SOURCE configuration option to EPSG to use official parameters (overriding the ones from GeoTIFF keys), or to GEOKEYS to use custom values from GeoTIFF keys and drop the EPSG code.
ERROR 1: PROJ: proj_create_from_database: C:\OSGeo4W\share\proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 1 whereas a number >= 3 is expected. It comes from another PROJ installation.
ERROR 6: Cannot find coordinate operations from `ENGCRS["unnamed",EDATUM["Unknown engineering datum"],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]' to `+proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs +type=crs'

Please can somebody help me?
Thank you
Regards.

**Comment by rouault** [comment]
That should rather be filed at https://trac.osgeo.org/osgeo4w/

**Comment by gpsaliola** [comment]
Thank you but https://trac.osgeo.org/ doesn't respond.

**Comment by neteler** [comment]
> Thank you but https://trac.osgeo.org/ doesn't respond.

I have just reported this issue to OSGeo-SAC (it is the osgeo7 server which is down).

**Comment by gpsaliola** [comment]
Thank you. I'll try later.

**Comment by gpsaliola** [comment]
The sites are back online.
I'm doing an unattended installation.
The only sites suggested for download are:
https://download.osgeo.org
https://ftp.osuosl.org
https://www.norbit.de

https://trac.osgeo.org/ is not mentioned.
Thanks.

**Comment by gpsaliola** [comment]
After further investigation I noticed that the problem only exists in the first installation (folder c.\OSGeo4W doesn't exist).
If you update a previous installation everything works.

**Comment by gpsaliola** [comment]
This topic has been close but the problem was not resolved.

**Comment by gpsaliola** [comment]
The topic has been closed but the problem has not been resolved.
