### ISSUE TITLE
GeoForAll logo not working, broke image upload and crop

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#40]
Filling in details for http://osgeo.getinteractive.nl/geo-for-all-labs/ngi/

And I cannot define the logo for the lab by selecting an existing photo:

<img width="961" alt="broken" src="https://user-images.githubusercontent.com/629681/29282563-43c41cb2-80f1-11e7-9769-5d0da2efc2b8.png">

**Comment by svandenhaak** [comment]
Hi Jody, is this still an issue? There have been some changes to the crop function in between now, and when this issue was first reported. I've just tried to reproduce the issue, but it seems to be working fine now. If it's working correctly for you as well, this ticket can be closed.

**Comment by jodygarnett** [comment]
If it is working fine for you please close, we can always reopen if the problem is reproducible with a specific image.

**Comment by svandenhaak** [comment]
I did indeed try it with the page and image mentioned above.
