### ISSUE TITLE
Spanish Language Chapter location

### ISSUE THREAD

**Issue by Delawen** [OSGeo/osgeo#46]
So, how do I add location when location is several places at the same time?

On our case: "Spain, Andorra, Argentina, Bolivia, Chile, Colombia, Costa Rica, Cuba, Dominican Republic, Ecuador, El Salvador, Guatemala, Honduras, Mexico, Nicaragua, Panama, Paraguay, Puerto Rico, Uruguay, Venezuela, United States, Equatorial Guinea"

Can we add more than one Location per chapter?

I tried to do the dirty workaround of creating a location that big... but it didn't work. Some error on the database. Probably name too big.

Or maybe allow a null location. We are mostly virtual, no location.

**Comment by jodygarnett** [comment]
I have added this into the issue tracker once before, it also effects service providers.

The current location fields are insufficient. I had hoped we could list a multi point for these cases?

Given how location has been factored out into a seperate content type we may need to rephrase this requirement.

**Comment by Delawen** [comment]
I think the best option should be to have multiple locations with maybe a main location as the contact point.

Worst case: "Location: worldwide" which also would fit our usecase.

**Comment by jodygarnett** [comment]
Or Null Island :)

**Comment by Delawen** [comment]
I created a worlwide placed in null island :)
