### ISSUE TITLE
Convert Bird's Eye View to Service Provider

### ISSUE THREAD

**Issue by jj0hns0n** [OSGeo/osgeo#47]
http://osgeo.getinteractive.nl/geo-for-all-labs/birds-eye-view/ ... should be a service provider not a GeoForAll Lab

**Comment by jodygarnett** [comment]
Think we will need to cut and paste this one

**Comment by jeffreylasut** [comment]
@jj0hns0n @jodygarnett I can't find Birds eye view anymore, it's not in service providers and not in GeoForAll Labs.
Did one of you moved this page already?

**Comment by jodygarnett** [comment]
I can see it in the GeoForAll Labs "trash" category - consisting of "Bird's Eye View" and "Get Interactive" entries.

Not sure, I note that there may be some confusion around this stuff still:
- http://osgeo.getinteractive.nl/geo-for-all-labs/comunidad-gvsig-uruguay/
