### ISSUE TITLE
default thumbnail/snippet image should be OSGeo Logo or correct image

### ISSUE THREAD

**Issue by jj0hns0n** [OSGeo/osgeo#49]
See when shared via Facebook. Should NOT be GeoCat image.

<img width="401" alt="screen shot 2017-08-14 at 16 00 45" src="https://user-images.githubusercontent.com/506078/29295528-bf62ec96-8109-11e7-8a31-e41add0069c1.png">

And this one SHOULD be GeoCat, but not GeoSolutions :)

<img width="218" alt="screen shot 2017-08-14 at 16 01 10" src="https://user-images.githubusercontent.com/506078/29295542-cd9bdc82-8109-11e7-8858-8c942a4d4f14.png">

**Comment by Delawen** [comment]
:roll_eyes:

**Comment by jeffreylasut** [comment]
We configured the Yoast plugin to give OSGeo logo as default, but you can configure each page to have a different image.
