### ISSUE TITLE
SEO Analysis wrong/inconsistent

### ISSUE THREAD

**Issue by Delawen** [OSGeo/osgeo#50]
![image](https://user-images.githubusercontent.com/726590/29296434-92f9cc6e-815a-11e7-82b6-7b2f18c5f609.png)

What text? 

https://kb.yoast.com/kb/error-text-contains-0-words/

_"f you’re using a page builder that does not share their content, please contact their development team to request compatibility with the Yoast SEO keyword analysis. They can learn more about this functionality here."_

**Comment by jj0hns0n** [comment]
@jeffreylasut can we just turn off this plugin for now please?

**Comment by jodygarnett** [comment]
@Delawen do you have the page that made that mistake? I have found the SEO to work "okay", but I do not think we pay for it long term so I expect it to go away.

**Comment by Delawen** [comment]
The GeoNetwork page.

I cannot find anything else to fill, but still it is there.

**Comment by jj0hns0n** [comment]
I've CC'd GET and ask them to turn it off. This plugin isn't really
providing much value now. We can revisit SEO later.

**Comment by jeffreylasut** [comment]
@svandenhaak please turn off the plugin.

**Comment by svandenhaak** [comment]
There are a couple of Yoast functions we make use of; the breadcrumbs, and the ability to select a primary tag/category (which is used to determine a project's position in the mega menu). Turning the plugin off would disable those functions, so I'll leave the plugin on for now.

**Comment by svandenhaak** [comment]
The Yoast plugin should now provide an accurate analysis.
