### ISSUE TITLE
Where is the page about incubation

### ISSUE THREAD

**Issue by jj0hns0n** [OSGeo/osgeo#52]
@jodygarnett where should this go in the IA?

**Comment by jodygarnett** [comment]
Look in the site map spreadsheet we have some things to move around.

**Comment by jodygarnett** [comment]
See #55

**Comment by jodygarnett** [comment]
I manually ported the content over so we would have something:
- http://osgeo.getinteractive.nl/about/committees/incubation/

This was marked in the site map for migration, not sure how migration is going.
