### ISSUE TITLE
MouseOver text on images has no valuable information (just shows filename)

### ISSUE THREAD

**Issue by gisnederland** [OSGeo/osgeo#77]
Case:
When hovering over images (such as logos) the "title" attribute of the image is shown.
Currently, that's in all (?) cases simply the filename of the image, such as _GeoCat-1_740x412_acf_cropped-370x206.png_.
Apparently taken from the title attribute, which seems to be a copy of the "alt" attribute.

Solution: 
either remove entirely, or replace the title attributes with more valuable information.

**Comment by MarvinGI** [comment]
Title now shows the name of the entity it is related to.
