### ISSUE TITLE
osgeo_live_letter.pdf file seams to be invalid

### ISSUE THREAD

**Issue by astroidex** [OSGeo/osgeo#80]
* can't open https://github.com/OSGeo/osgeo/blob/master/marketing/print/osgeo_live_letter.pdf
* better rename the file to osgeolive_letter.pdf

**Comment by jodygarnett** [comment]
This works for me, is it resolved for you? (Please note that not all browsers can render each PDF in frame, what browser are you using?)

**Comment by astroidex** [comment]
sorry for the late answer. works fine now.
