### ISSUE TITLE
News Item share this heading empty

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#81]
Assume this is simply not done yet.

Here is an example page:

http://osgeo.getinteractive.nl/foundation-news/geo4africa-2017/

**Comment by MarvinGI** [comment]
We now have added the share this buttons.

**Comment by jodygarnett** [comment]
Not sure I see it yet?

**Comment by MarvinGI** [comment]
It should look like this:

![screenshot from 2017-09-06 14-27-13](https://user-images.githubusercontent.com/22152296/30111833-84a207aa-930f-11e7-90c5-a4a95b4b8b70.png)

Maybe you are viewing a old cached version. You can try emptying the cache or visiting the page in incognito.
