### ISSUE TITLE
News item links are not visible, only shown on hover, making discovery hard

### ISSUE THREAD

**Issue by jsanz** [OSGeo/osgeo#83]
Website (at least in the news items) don't display links, only on hover. This makes hard for users to follow links to resources and such.

[Example post](http://osgeo.getinteractive.nl/foundation-news/geomoose-3-0-0-released/) 

![2017-08-28_18 04 49-selection](https://user-images.githubusercontent.com/188264/29795732-7e318648-8c1b-11e7-9928-2103d3f6e1f2.png)

Link only visible on hover

![2017-08-28_18 05 16-selection](https://user-images.githubusercontent.com/188264/29795734-8243fb30-8c1b-11e7-8177-0f8a5b43fbed.png)

**Comment by MarvinGI** [comment]
The content wasn't filled the right way. It contained div tags which aren't suppose to be there. I assume the content was copypasted in. I removed the tags that weren't suppose to be there, and now it seems to work as intended.

**Comment by jsanz** [comment]
Oh, my bad, thanks @MarvinGI !!
