### ISSUE TITLE
grass gis showing up in mega menu multiple times

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#84]
grass gis is currently listed as the following project types:

* Desktop Application (primary)
* Geospatial Library
* Spatial Database

There are two solutions to this:

* Use *Primary* to determine location of an OSGeo project in the mega menu
* Make **Project Type** single selection

**Comment by jodygarnett** [comment]
This issue has a workaround, only selecting single project type, as such it can be a lower priority.

**Comment by neteler** [comment]
Not sure what needs to be done here. Primary is used.

**Comment by jodygarnett** [comment]
You are okay @neteler - remember we made this content to test out the design. This bug report is for the vendor get interactive to work on. I was testing the website and reporting issues for tomorrows meeting.

**Comment by svandenhaak** [comment]
This issue has been fixed, using the first solution (_Use Primary to determine location of an OSGeo project in the mega menu_).
