### ISSUE TITLE
grass gis logo showing up under action buttons

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#85]
For the following page: http://osgeo.getinteractive.nl/projects/grass-gis/

The logo is tall, rather than wide, and extends outside of its white box under the visit our website and donate button.

![grass-glitch](https://user-images.githubusercontent.com/629681/29857032-46230696-8d0b-11e7-9c9d-43973f985201.png)

**Comment by neteler** [comment]
Yes, it looks ugly like that. I tried to fix it with the internal image editor (crop) to no avail:

Warning: The selected image is smaller than the required size!
Width should be at least: 740px
Selected image width: 557px

But that is the size:
http://osgeo.getinteractive.nl/wp-admin/upload.php?item=3096
File name: grassgis_only_vector_font_white_middle-1.png
File type: image/png
Uploaded on: August 21, 2017
File size: 48 KB
Dimensions: 557 × 750  <---

Any ideas how to fix that? Thanks

**Comment by jodygarnett** [comment]
Not yet, hence the bug report. Perhaps we will get a template fix, or perhaps a logo size guide.

**Comment by svandenhaak** [comment]
This issue has been fixed (template fix). 

@neteler the image has a width of 557px, and a height of 750px, which is why you received the warning about the image being smaller than required.
