### ISSUE TITLE
Projects Listing sort order: OSGeo Project > OSGeo Community > Other

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#87]
Projects listing sort order.

Carry on from https://github.com/OSGeo/osgeo/issues/68

**Comment by jodygarnett** [comment]
We have some other requests:
- We have a request to sort by popularity (github starts from the QGIS team)
- Sort by numbers contributors (from the science team)
- Looking for an objective way to sort.

From meeting:
- Group By project type (OSGeo Project > OSGeo Community > Other)
- Alphabetical

**Comment by jodygarnett** [comment]
This is really not an enhancement it has been a requirement to list OSGeo Project > Community Projects > Other from the git go. This bug report stems from the functionality not being implemented yet.

**Comment by MarvinGI** [comment]
We have added the group by project type and alphabetical order to project. We have moved the requests to an other issue: #91

**Comment by jodygarnett** [comment]
Thanks, and yes #91 is an enhancement (that I am not sure we will act on)

**Comment by MarvinGI** [comment]
I overlooked that one. I added the sorting now, so it should show the right order.
