### ISSUE TITLE
Choose a project tag system not working to reduce search space

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/osgeo#88]
The tags are currently additive listing too much information, rather than restricting the search set to assist people find what is needed.

As an example the Publish > Catalog page lists the following tags:

```
publish -service
publish -catalog
```

However all tags for `publish` are listed showing unrelated tags such as `publish -document`, `publish -service` and `publish -data`

**Comment by MarvinGI** [comment]
We don't understand the issue, could you elaborate?

**Comment by jodygarnett** [comment]
I have gone over this a couple of times in the weekly meetings, let me use an example.

Let's start with the **Topics** list from https://github.com/OSGeo/osgeo/issues/19

```
Publish
- Content Management
- Catalog
- Data
Mapping and Cartogrpahy
- Desktop Mapping
- Mapping Services
- Mobile Mapping
Analysis and Processing
- Desktop Anaysis
- Web Processing
- Data Query
- Raster Processing
Information Technology
- Data
- Web Services
- Client
- Cloud
- Portal
Development
- Web Development
- Tools
- Libraries
- Mobile Development
```  

This represents your search space, https://github.com/OSGeo/osgeo/issues/19 solves this problem by making a unique tag for each leaf in the above tree.

This issue represents the original approach using tags and multiple searches to obtain the correct result.

Please read [Choose a project contents](https://docs.google.com/spreadsheets/d/1m15SP03qbgCVErle2R1uGx0c5O8q94JtiOr1yCV9O20/edit?usp=sharing) for following list of tags:

```
Publish
- Content Management        publish+document
- Catalog                   publish+catalog
- Data                      publish+service+raster; publish+service+vector
Mapping and Cartogrpahy  
- Desktop Mapping           cartography+desktop
- Mapping Services          cartography+service
- Mobile Mapping            cartography+mobile
Analysis and Processing
- Desktop Anaysis           process+desktop
- Web Processing            process+service
- Data Query                process+vector
- Raster Processing         process+raster
Information Technology
- Data                      it+database; it+bigdata 
- Web Services              it+service
- Client                    it+web; it+desktop; it+mobile
- Cloud                     it+cloud
- Portal                    it+portal
Development
- Web Development           devlop+browser
- Tools                     develop+tools
- Libraries                 develop+library
- Mobile Development        develop+mobile
```  

You can see how the same search space, but it is accomplished by using a smaller number of tags - reusing Level 2 tags (like raster, vector, service, ...) within each Level 1 tag (publish, cartography, process, ...).

**Comment by jeffreylasut** [comment]
@jodygarnett @MarvinGI Sorry guys during Foss4g I already did some work for this.

@MarvinGI I pushed the changes to template-project-wizard-results.php, it still needs some testing.

@jodygarnett The Data example is confusing me a bit:
Data                      publish+service+raster; publish+service+vector
At Foss4g we created this example:
it + (web|desktop|mobile)
Can I translate the data example like this:
publish + (service|raster|vector)

**Comment by jodygarnett** [comment]
We have reduced this to only use and statements.

*This involves the creation of a Level 2 "client" and "data" tag which we will need to apply
* We now publish

**Comment by jodygarnett** [comment]
Note Leve 2 - is repersented as "Level 2" and "Development" - do you want to combine those?

**Comment by svandenhaak** [comment]
Replaced the 'or' statement with an 'and' statement, so only projects which have all the required tags are shown.

**Comment by jodygarnett** [comment]
Thanks, that and migrating tags should do the trick, can we hold this ticket open until the pages work.

**Comment by jeffreylasut** [comment]
@jodygarnett This is tested by us and should work now, that's why I closed this ticket.

**Comment by jodygarnett** [comment]
@jeffreylasut I am having some trouble with nothing being listed on the http://osgeo.getinteractive.nl/choose-a-project/information-technology/client/ page.

Can I get some help in tomorrows meeting?

The QGIS and gvSig projects should show up there.

**Comment by jodygarnett** [comment]
Marking this issue (use of tags) closed, the confirmation of content has been moved to #141 above.

Issue #19 remains open, giving an unambiguous way for projects to control what page they are listed on.

**Comment by jodygarnett** [comment]
Can we close this this, the two issues are now seperate:

- #19 addresses the maintenance issue, helping projects list themselves on purpose 
- #141 addresses the content issue, verifying the projects listed are correct
