### ISSUE TITLE
create link to other webside for an event via Call-2-actions does not work anymore

### ISSUE THREAD

**Issue by astroidex** [OSGeo/osgeo#98]
* somehow for events it does not work to create an external link via Call-2-actions

* it worked for the page (created some weeks ago) http://osgeo.getinteractive.nl/events/intergeo-2017/

* it does not work for the page http://osgeo.getinteractive.nl/events/osgeo-code-sprint-2018/ 
-> Problem I only can add links to the internal pages

**Comment by MarvinGI** [comment]
It works for me. I added a test button to http://osgeo.getinteractive.nl/events/osgeo-code-sprint-2018/

Could you check if it still doesn't work for you?

**Comment by astroidex** [comment]
Works fine now. Do not know why it did not work before. Thanks for your help.
